FROM python:3.10

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY Streamlit/Streamlit_app.py Streamlit_app.py

EXPOSE 8501

CMD ["streamlit", "run", "Streamlit_app.py"]